name: "PR — CI (build · lint · test)"

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  id-token: write

jobs:
  test:
    name: Test (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Build
        run: npm run build --if-present
      - name: Lint
        run: npm run lint --if-present
      - name: Test
        # run in-band to increase compatibility on constrained runners if needed
        run: npm test --silent
