name: "Publish · npm (on release)"

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

concurrency:
  group: publish-npm
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate
          yarn --version

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build
        run: npm run build --if-present

      - name: Set npm auth token
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public
